{{- if .Values.gazer.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-lazy-koala-pv
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
{{- end }}