apiVersion: v1
kind: Namespace
metadata:
  name: lazy-koala
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gazer
  namespace: lazy-koala
  labels:
    app: gazer
spec:
  selector:
    matchLabels:
      name: gazer
  template:
    metadata:
      labels:
        name: gazer
    spec:
      containers:
        - name: gazer
          #          command: [ "sh", "-c", "sleep 60d" ]
          image: ghcr.io/mrsupiri/lazy-koala/gazer:1644303713
          ports:
            - containerPort: 8000
              name: metrics
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              ephemeral-storage: "2Gi"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONWARNINGS
              value: "ignore:Unverified HTTPS request"
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: lsb-release
              mountPath: /etc/lsb-release.host
              readOnly: false
            - name: os-release
              mountPath: /etc/os-release.host
              readOnly: false
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: modules-host
              mountPath: /lib/modules.host
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: boot-host
              mountPath: /boot.host
              readOnly: false
            - name: debug
              mountPath: /sys/kernel/debug
              readOnly: false
            - name: config
              mountPath: "/gazer/config"
              readOnly: true
      hostNetwork: true
      hostPID: true
      serviceAccountName: lazy-koala
      initContainers:
        - name: init-headers
          image: ghcr.io/mrsupiri/lazy-koala/gazer:init
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: [ "SYS_ADMIN" ]
          volumeMounts:
            - name: lsb-release
              mountPath: /etc/lsb-release.host
              readOnly: false
            - name: os-release
              mountPath: /etc/os-release.host
              readOnly: false
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: modules-host
              mountPath: /lib/modules.host
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: boot-host
              mountPath: /boot.host
              readOnly: false
      volumes:
        - name: lsb-release
          hostPath:
            path: /etc/lsb-release
        - name: os-release
          hostPath:
            path: /etc/os-release
        - name: modules-dir
          hostPath:
            path: /var/cache/linux-headers/modules_dir
        - name: linux-headers-generated
          hostPath:
            path: /var/cache/linux-headers/generated
        - name: boot-host
          hostPath:
            path: /
        - name: modules-host
          hostPath:
            path: /lib/modules
        - name: debug
          hostPath:
            path: /sys/kernel/debug
        - name: config
          configMap:
            name: gazer-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: lazy-koala
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: lazy-koala
      containers:
      - name: prometheus
#        command: [ "sh", "-c", "sleep 60d" ]
        image: prom/prometheus:v2.33.1
        ports:
        - containerPort: 9090
          name: default
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
         name: prometheus-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lazy-koala
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get
  - apiGroups: [ "" ]
    resources:
      - nodes
      - services
      - endpoints
      - pods
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - podmetrics
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lazy-koala
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lazy-koala
subjects:
  - kind: ServiceAccount
    name: lazy-koala
    namespace: lazy-koala
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lazy-koala
  namespace: lazy-koala
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lazy-koala
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'lazy-koala'
        scrape_interval: 1s
        metrics_path: /
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          regex: metrics
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: gazer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gazer-config
  namespace: lazy-koala
data:
  config.yaml: |
    10.244.0.7:
      name: service-1-aaf5fced-749b94b988-9h7jz
      serviceName: service-1
      namespace: default
      node: minikube
    10.244.0.6:
      name: service-2-aaf5fced-cf6647556-vpwzk
      serviceName: service-2
      namespace: default
      node: minikube
    10.244.0.3:
      name: service-3-aaf5fced-5478b64d59-k956v
      serviceName: service-3
      namespace: default
      node: minikube
    10.244.0.4:
      name: service-4-aaf5fced-656b456747-tr7nc
      serviceName: service-4
      namespace: default
      node: minikube