{{- if .Values.sherlock.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sherlock.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lazy-koala.labels" . | nindent 4 }}
    lazykoala: sherlock
  {{- with .Values.sherlock.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}