{{- if .Values.gazer.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gazer
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - podmetrics
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - lazykoala.isala.me
    resources:
    - inspectors
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
{{- end }}