{{- if .Values.gazer.create -}}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "lazy-koala.selectorLabels" . | nindent 4 }}
    lazykoala: prometheus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
{{- end }}