{{- if .Values.gazer.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gazer.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lazy-koala.labels" . | nindent 4 }}
    lazykoala: gazer
  {{- with .Values.gazer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}