{{- if .Values.gazer.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lazy-koala
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lazy-koala
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}