{{- if .Values.operator.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lazy-koala.labels" . | nindent 4 }}
    lazykoala: operator
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}