{{- if .Values.operator.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccountName }}
  labels:
    {{- include "lazy-koala.labels" . | nindent 4 }}
    lazykoala: operator
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.gazer.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gazer.serviceAccountName }}
  labels:
    {{- include "lazy-koala.labels" . | nindent 4 }}
    lazykoala: gazer
  {{- with .Values.gazer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.sherlock.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sherlock.serviceAccountName }}
  labels:
    {{- include "lazy-koala.labels" . | nindent 4 }}
    lazykoala: sherlock
  {{- with .Values.sherlock.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}