name: release

on: workflow_dispatch

jobs:
  publish:
    name: Create GH Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Release
        uses: go-semantic-release/action@master
        with:
          github-token: ${{ secrets.TOKEN }}
          prepend: true
          changelog-file: CHANGELOG.md
      - name: Update CHANGELOG.md
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "docs: Update the changelog"
          git push origin